# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydict',
            options={'verbose_name': '\u8bfe\u7a0b\u7c7b\u522b', 'verbose_name_plural': '\u8bfe\u7a0b\u7c7b\u522b'},
        ),
        migrations.AlterModelOptions(
            name='orientdict',
            options={'verbose_name': '\u8bfe\u7a0b\u65b9\u5411', 'verbose_name_plural': '\u8bfe\u7a0b\u65b9\u5411'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
