# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170411_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '\u8bfe\u7a0b\u7ae0\u8282', 'verbose_name_plural': '\u8bfe\u7a0b\u7ae0\u8282'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u8bfe\u7a0b\u89c6\u9891', 'verbose_name_plural': '\u8bfe\u7a0b\u89c6\u9891'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='\u7ae0\u8282\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='video',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='video',
            name='praise_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u4eba\u6570'),
        ),
    ]
