# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170412_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='video/%Y/%m', verbose_name='\u4e0a\u4f20\u89c6\u9891'),
        ),
    ]
