# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-12 12:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20170412_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u8bfe\u7a0b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5b66\u4e60\u8fc7\u7684\u8bfe\u7a0b',
                'verbose_name_plural': '\u7528\u6237\u5b66\u4e60\u8fc7\u7684\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.FloatField(default=0, verbose_name='\u6253\u8d4f\u91d1\u989d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Video', verbose_name='\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5b66\u4e60\u8fc7\u7684\u89c6\u9891',
                'verbose_name_plural': '\u7528\u6237\u5b66\u4e60\u8fc7\u7684\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, verbose_name='\u53d1\u8868\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Video', verbose_name='\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53d1\u8868\u7684\u8bc4\u8bba',
                'verbose_name_plural': '\u7528\u6237\u53d1\u8868\u7684\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='VideoFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Video', verbose_name='\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf\u7684\u89c6\u9891',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf\u7684\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='VideoPraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Video', verbose_name='\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u70b9\u8d5e\u7684\u89c6\u9891',
                'verbose_name_plural': '\u7528\u6237\u70b9\u8d5e\u7684\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='VideoRegard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regard', models.FloatField(verbose_name='\u6253\u8d4f\u91d1\u989d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Video', verbose_name='\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6253\u8d4f',
                'verbose_name_plural': '\u7528\u6237\u6253\u8d4f',
            },
        ),
    ]
